### ISSUE TITLE
Spade reputation Service

### ISSUE THREAD

**Issue by jcace** [data-preservation-programs/spade-sp-source#1]
- Set up the Spade Reputation Service repo, readme, `main.go` etc 
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/spade-reputation-service/issues/6
- [ ] https://github.com/data-preservation-programs/spade-reputation-service/issues/5
- [ ] https://github.com/data-preservation-programs/spade-reputation-service/issues/3
```
ETA: 2023-12-15
